### ISSUE TITLE
Named slots don't work?

### ISSUE THREAD

**Issue by jods4** [jods4/aurelia-webpack-build#10]
Posted by @ovi2 in aurelia/skeleton-navigation#714

I've start using it in my project, but I encountered a small problem. I have few components that are using named slots. Build get successfully, but I get an error at run time
Do I miss something or this is an issue?
I must specify that if unnamed slots are used this is working fine.

```
Uncaught (in promise) Error: Error invoking SlotCustomAttribute. Check the inner error for details.
Inner Error:
Message: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
Inner Error Stack:
Error: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
    at validateKey (file:///C:/work/sandbox/webpackbuild/aurelia-webpack-build/demos/02-Traced_deps/dist/bundle.js:8241:11)
    at Container.get (file:///C:/work/sandbox/webpackbuild/aurelia-webpack-build/demos/02-Traced_deps/dist/bundle.js:8438:5)
    at Container.elementContainerGet [as get] (file:///C:/work/sandbox/webpackbuild/aurelia-webpack-build/demos/02-Traced_deps/dist/bundle.js:2294:15)
    at Object.invoke (file:///C:/work/sandbox/webpackbuild/aurelia-webpack-build/demos/02-Traced_deps/dist/bundle.js:8290:31)
    at InvocationHandler.invoke (file:///C:/work/sandbox/webpackbuild/aurelia-webpack-build/demos/02-Traced_deps/dist/bundle.js:8261:166)
    at Container.invoke (file:///C:/work/sandbox/webpackbuild/aurelia-webpack-build/demos/02-Traced_deps/dist/bundle.js:8525:23)
    at ProviderResolver.get (file:///C:/work/sandbox/webpackbuild/aurelia-webpack-build/demos/02-Traced_deps/dist/bundle.js:2239:72)
    at Container.get (file:///C:/work/sandbox/webpackbuild/aurelia-webpack-build/demos/02-Traced_deps/dist/bundle.js:8464:21)
    at Container.elementContainerGet [as get] (file:///C:/work/sandbox/webpackbuild/aurelia-webpack-build/demos/02-Traced_deps/dist/bundle.js:2294:15)
    at HtmlBehaviorResource.create (file:///C:/work/sandbox/webpackbuild/aurelia-webpack-build/demos/02-Traced_deps/dist/bundle.js:4246:56)
End Inner Error Stack
```

**Comment by jods4** [comment]
I don't see how this can be related to modules at all.

From your call stack, I suppose `this.target` is `null` on this line:
https://github.com/aurelia/templating/blob/master/src/html-behavior.js#L317

But I'm not sure why it could be.

@EisenbergEffect You know the inner workings of slots well, any idea what could cause this?

**Comment by nmocruz** [comment]
@jods4  I'm getting this one to. It seams like is related to this. 
https://github.com/aurelia/pal-browser/issues/17

**Comment by jods4** [comment]
It's exactly the same situation, error message and call stack indeed.

I'm going to close this issue and follow aurelia/pal-browser#17. It reproduces on JSPM so it may not be directly related to the build process. If the resolution is to adjust the JSPM build I'll adjust our webpack plugin accordingly.
